version: '3.9'

services:


  postgres-db:
    container_name: post
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=medicine
    ports:
      - "5439:5432"
    volumes:
      - db:/data/postgres
    networks:
      - healthserve

    
  migrate:
    image: migrate/migrate
    networks:
      - healthserve
    volumes:
      - ./migrations:/migrations
    depends_on:
      - postgres-db
    command: ["-path", "/migrations", "-database" ,"postgres://postgres:1234@post:5432/medicine?sslmode=disable","up"]

  userservice:
    container_name: auth
    build: .
    ports:
      - "8081:8081"
      - "50051:50051"
    networks:
     - healthserve
    depends_on:
      - postgres-db

networks:
  healthserve:
    external: true

volumes:
  db:
  